apiVersion: v1
kind: Service
metadata:
  name: node-app-service
  namespace: node-app
spec:
  type: ClusterIP
  selector:
    app: node-app
  ports:
    - port: 80        # service port
      targetPort: 8000  # c
